apiVersion: apps/v1
kind: Deployment

metadata:
  name: incident-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: incident-api

  template:
    metadata:
      labels:
        app: incident-api

    spec:
      containers:
      - name: incident-api

        image: siddhi1819/incident-api:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

        env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: incident-api-config
                key: ENVIRONMENT

          - name: APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: incident-api-config
                key: APPLICATION_NAME